<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookingSeeder extends Seeder
{
    public function run(): void
    {
        $bookings = [
            [
                'user_id' => 2,
                'event_id' => 1,
                'venue_id' => null,
                'location' => 'Central Park',
                'name' => 'Summer Music Festival Booking',
                'booking_date' => '2025-07-01',
                'booking_start_time' => '14:00:00',
                'booking_end_time' => '23:00:00',
                'platform_rate' => 500.00,
                'fee_percentage' => 17.00,
                'fee_amount' => 85.00,
                'net_amount' => 415.00,
                'info' => 'Paid 24h after event completion',
                'status' => 'booked',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'event_id' => null,
                'venue_id' => 1,
                'location' => '123 Main St, Cityville',
                'name' => 'Grand Ballroom Booking',
                'booking_date' => '2025-06-30',
                'booking_start_time' => '08:00:00',
                'booking_end_time' => '23:00:00',
                'platform_rate' => 500.00,
                'fee_percentage' => 17.00,
                'fee_amount' => 85.00,
                'net_amount' => 415.00,
                'info' => 'Paid 24h after event completion',
                'status' => 'upcoming',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'event_id' => 3,
                'venue_id' => null,
                'location' => 'Downtown Theater',
                'name' => 'Comedy Night Booking',
                'booking_date' => '2025-05-30',
                'booking_start_time' => '20:00:00',
                'booking_end_time' => '23:30:00',
                'platform_rate' => 500.00,
                'fee_percentage' => 17.00,
                'fee_amount' => 85.00,
                'net_amount' => 415.00,
                'info' => 'Paid 24h after event completion',
                'status' => 'in-progress',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'event_id' => null,
                'venue_id' => 2,
                'location' => '456 Market St, Cityville',
                'name' => 'Downtown Conference Center Booking',
                'booking_date' => '2025-05-30',
                'booking_start_time' => '07:00:00',
                'booking_end_time' => '21:00:00',
                'platform_rate' => 500.00,
                'fee_percentage' => 17.00,
                'fee_amount' => 85.00,
                'net_amount' => 415.00,
                'info' => 'Paid 24h after event completion',
                'status' => 'in-progress',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'event_id' => 5,
                'venue_id' => null,
                'location' => 'City Hall Auditorium',
                'name' => 'Dance Gala Booking',
                'booking_date' => '2025-05-30',
                'booking_start_time' => '19:00:00',
                'booking_end_time' => '22:00:00',
                'platform_rate' => 500.00,
                'fee_percentage' => 17.00,
                'fee_amount' => 85.00,
                'net_amount' => 415.00,
                'info' => 'Paid 24h after event completion',
                'status' => 'completed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'event_id' => null,
                'venue_id' => 3,
                'location' => '789 Garden Ave, Cityville',
                'name' => 'Open Air Garden Booking',
                'booking_date' => '2025-06-30',
                'booking_start_time' => '09:00:00',
                'booking_end_time' => '20:00:00',
                'platform_rate' => 500.00,
                'fee_percentage' => 17.00,
                'fee_amount' => 85.00,
                'net_amount' => 415.00,
                'info' => 'Paid 24h after event completion',
                'status' => 'booked',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'event_id' => 2,
                'venue_id' => null,
                'location' => 'Grand Convention Center',
                'name' => 'Business Conference Booking',
                'booking_date' => '2025-05-30',
                'booking_start_time' => '09:00:00',
                'booking_end_time' => '18:00:00',
                'platform_rate' => 500.00,
                'fee_percentage' => 17.00,
                'fee_amount' => 85.00,
                'net_amount' => 415.00,
                'info' => 'Paid 24h after event completion',
                'status' => 'upcoming',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'event_id' => null,
                'venue_id' => 4,
                'location' => '101 City Hall Rd, Cityville',
                'name' => 'City Hall Auditorium Booking',
                'booking_date' => '2025-05-29',
                'booking_start_time' => '10:00:00',
                'booking_end_time' => '22:00:00',
                'platform_rate' => 500.00,
                'fee_percentage' => 17.00,
                'fee_amount' => 85.00,
                'net_amount' => 415.00,
                'info' => 'Paid 24h after event completion',
                'status' => 'in-progress',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'event_id' => null,
                'venue_id' => 5,
                'location' => '202 Skyline Blvd, Cityville',
                'name' => 'Rooftop Terrace Booking',
                'booking_date' => '2025-05-30',
                'booking_start_time' => '16:00:00',
                'booking_end_time' => '23:59:59',
                'platform_rate' => 500.00,
                'fee_percentage' => 17.00,
                'fee_amount' => 85.00,
                'net_amount' => 415.00,
                'info' => 'Paid 24h after event completion',
                'status' => 'upcoming',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('bookings')->insert($bookings);
    }
}
